@startuml iof
skinparam class{
 BackgroundColor DFA702
 FontColor White
 FontStyle bold
}
skinparam object{
    BackgroundColor 76608A
    fontColor White
    BorderColor White    
}
@enduml