@startuml iof
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/main/ontologyv2.iuml
hide circle
skinparam class{
 BackgroundColor DFA702
 FontColor White
 FontStyle bold
}
skinparam object{
    BackgroundColor 76608A
    fontColor White
    BorderColor White    
}
!$namespace_colors = { "bfo" : "DFA702", 
                        "iof":"DodgerBlue", 
                        "ns":"Green", 
                        "ns1":"76608A"}
@enduml