@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, bfo:Object)
class(c2, bfo:Site)
class(c3, bfo:SpatialRegion)
class(c4, bfo:TemporalInstant)
class(c5, bfo:SpatioTemporalRegion)
individual(o1, ns1:powder-river-basin)
individual(o2, ns1:long-beach-port)
individual(o3, ns1:frieght-train)
individual(o4, ns1:spatial-region-powder-river-basin)
individual(o5, ns1:spatial-region-long-beach)
individual(o6, ns1:temporal-instant-powder-river-basin)
individual(o7, ns1:temporal-instant-long-beach)
individual(o8, ns1:spatio-temporal-1)
individual(o9, ns1:spatio-temporal-2)

assertDProperty(o1, rdfs:label, "Powder River Basin, Wyoming")
assertDProperty(o2, rdfs:label, "Port of Long Beach, California")
assertDProperty(o3, rdfs:label, "BNSF Frieght Train")
instanceOf(o1, c2)
instanceOf(o2, c2)
instanceOf(o3, c1)
instanceOf(o4, c3)
instanceOf(o5, c3)
instanceOf(o6, c4)
instanceOf(o7, c4)
instanceOf(o8, c5)
instanceOf(o9, c5)

assertOProperty(o3, bfo:locatedInAtSomeTime, o1, down)
assertOProperty(o3, bfo:locatedInAtSomeTime, o2, down)
assertOProperty(o3, bfo:existsAt, o6, up)
assertOProperty(o3, bfo:existsAt, o7, up)
assertOProperty(o1, bfo:occuiesSpatialRegionAtAllTimes, o4, up)
assertOProperty(o2, bfo:occuiesSpatialRegionAtAllTimes, o5, up)
assertOProperty(o8, bfo:temporallyProjectsOnto, o6, up)
assertOProperty(o9, bfo:temporallyProjectsOnto, o7, up)
assertOProperty(o8, bfo:spatiallyProjectsOntoAtAllTimes, o4, up)
assertOProperty(o9, bfo:temporallyProjectsOnto, o5, up)
@enduml