@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c3, "iof:Mass")
class(c4, "iof:MeasuredValueExpression")
individual(o1, "ns1:mass1")
individual(o3, "ns1:mass-value")
instanceOf(o1, c3)
instanceOf(o3, c4)
assertOProperty(o3, iof:isMeasuredValueOfAtSomeTime, o1)
assertDProperty(o3, iof:hasSimpleExpressionValue, 100^xsd:integer)
@enduml