@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, "bfo:Quality")    
class(c2, "iof:PhysicalQuality")
class(c3, "ns:Temperature")
individual(o1, "ns1:temperature1")
individual(o2, "ns1:Object 2")
instanceOf(o2, c1)
instanceOf(o1, c2)
instanceOf(o1, c3)
@enduml