@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml

class(ms, iof:MaterialState)
class(p, bfo:process)
defineSubClass(ms, p)
class(ls, iof:LocationState)
defineSubClass(ls, ms)
class(o, bfo:object)
class(s, bfo:site)
class(sr, bfo:SpatialRegion)
equivalentOnly(ls, iof:hasObject, o)
equivalentOnly(ls, iof:hasLocaton, s)
individual(t, ns:train1)
instanceOf(t, o)
individual(st, ns:station1)
instanceOf(st, s)
individual(ls1, ns:location-state-of-train1)
instanceOf(ls1, ls)
assertOProperty(ls1, iof:hasObject, t)
assertOProperty(ls1, iof:hasLocation, st)
assertDProperty(ls1, iof:hasTime, 10:00PM)

individual(pt, ns:train-going-to-station1)
instanceOf(pt, p)
assertOProperty(pt, iof:hasOutputState, ls1)

class(ps, iof:PropertyState)

@enduml