@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, "bfo:Quality")    
class(c2, "iof:PhysicalQuality")
class(c3, "ns:Temperature")
individual(o1, "ns1:temperature1")
defineSubClass(c3, c2)
defineSubClass(c2, c1)
instanceOf(o1, c3)
@enduml