@startuml
!include C:\Users\arkop\git\IOF-Visual\ontopuml\iof.iuml
oClass(iof:PieceOfEquipment)
oClass(iof:Assembly)
oClass(iof:System)
oClass(ns1:Machine)
' union(m2, '["iof:PieceOfEquipment", "iof:Assembly", "iof:System"]')
' equivalent(m1, m2, down)
subUnion(ns1:Machine, '["iof:PieceOfEquipment", "iof:Assembly", "iof:System"]', left, left)

class(c1, bfo:Quality)
class(c2, bfo:Object)
equiDataOnly(c2, bfo:bears, xsd:double)  
@enduml