@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, bfo:Object)
class(c2, bfo:Site)
class(c3, bfo:SpatialRegion)
class(c4, bfo:TemporalInstant)
class(c5, bfo:SpatioTemporalRegion)
individual(o1, ns1:powder-river-basin)
individual(o2, ns1:long-beach-port)
individual(o3, ns1:frieght-train)
individual(o4, ns1:spatial-region-powder-river-basin)
individual(o5, ns1:spatial-region-long-beach)
individual(o6, ns1:temporal-instant-powder-river-basin)
individual(o7, ns1:temporal-instant-long-beach)
individual(o8, ns1:spatio-temporal-1)
individual(o9, ns1:spatio-temporal-2)

data(o1, rdfs:label, "Powder River Basin, Wyoming")
data(o2, rdfs:label, "Port of Long Beach, California")
data(o3, rdfs:label, "BNSF Frieght Train")
typeOf(o1, c2)
typeOf(o2, c2)
typeOf(o3, c1)
typeOf(o4, c3)
typeOf(o5, c3)
typeOf(o6, c4)
typeOf(o7, c4)
typeOf(o8, c5)
typeOf(o9, c5)

property(o3, bfo:locatedInAtSomeTime, o1, down)
property(o3, bfo:locatedInAtSomeTime, o2, down)
property(o3, bfo:existsAt, o6, up)
property(o3, bfo:existsAt, o7, up)
property(o1, bfo:occuiesSpatialRegionAtAllTimes, o4, up)
property(o2, bfo:occuiesSpatialRegionAtAllTimes, o5, up)
property(o8, bfo:temporallyProjectsOnto, o6, up)
property(o9, bfo:temporallyProjectsOnto, o7, up)
property(o8, bfo:spatiallyProjectsOntoAtAllTimes, o4, up)
property(o9, bfo:temporallyProjectsOnto, o5, up)
@enduml