@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
oClass(ns:Image)
oClass(iof:InformationContentEntity)
oClass(ns:File)
oClass(ns:FilePath)
oClass(iof:MeasurementInformationContentEntity)
oClass(iof:DesignativeInfomrationContentEntity)
oClass(iof:MeasurementProcess)
oClass(iof:PlannedProcess)
oClass(ns:Camera)
oClass(iof:PieceOfEquipment)
oClass(bfo:FiatObjectPart)
oClass(bfo:2DSpatialRegion)
oClass(bfo:1DSpatialRegion)
oClass(bfo:Object)
subClass(ns:Camera, iof:PieceOfEquipment)
subClass(ns:Image, iof:MeasurementInformationContentEntity)
subClass(ns:File, iof:InformationContentEntity)
subClass(ns:FilePath, iof:DesignativeInfomrationContentEntity)
xSome(ns:Image, iof:serializedIn, ns:File)
xSome(ns:FilePath, iof:designates, ns:File, "", right)

oIndividual(ns1:image)
oIndividual(ns1:file1)
oIndividual(ns1:file-path1)
typeOf(ns1:image, ns:Image)
typeOf(ns1:file1, ns:File)
typeOf(ns1:file-path1, ns:FilePath)
property(ns1:image, iof:serializedIn, ns1:file1)
property(ns1:file-path1, iof:designates, ns1:file1, right)
data(ns1:file-path1, rdfs:label, "C:\user\folder\file1")

oIndividual(ns1:part1)
typeOf(ns1:part1, bfo:Object)
oIndividual(ns1:layer1)
typeOf(ns1:layer1, bfo:2DSpatialRegion)
oIndividual(ns1:meltpool-location)
typeOf(ns1:meltpool-location, bfo:1DSpatialRegion)
oIndividual(ns1:meltpool)
typeOf(ns1:meltpool, bfo:FiatObjectPart)
property(ns1:meltpool, bfo:continuantPartOf, ns1:meltpool-location, up)
property(ns1:meltpool-location, bfo:continuantPartOf, ns1:layer1, up)
property(ns1:layer1, bfo:continuantPartOf, ns1:part1, up)

oIndividual(ns1:imaging)
typeOf(ns1:imaging, iof:MeasurementProcess)
typeOf(ns1:imaging, iof:PlannedProcess)
oIndividual(ns1:camera1)
typeOf(ns1:camera1, ns:Camera)
property(ns1:imaging, iof:hasParticipant, ns1:camera1, down)
property(ns1:image, iof:isOutputOf, ns1:imaging, down)
property(ns1:image, iof:isAbout, ns1:meltpool, down)
@enduml