@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
oClass(ns:Model)
oClass(iof:InformationContentEntity)
oClass(ns:File)
oClass(ns:FilePath)
oClass(iof:DesignativeInfomrationContentEntity)
subClass(ns:Model, iof:InformationContentEntity)
subClass(ns:File, iof:InformationContentEntity)
subClass(ns:FilePath, iof:DesignativeInfomrationContentEntity)
xSome(ns:Model, iof:serializedIn, ns:File)
xSome(ns:FilePath, iof:designates, ns:File, "", right)

oIndividual(ns1:system-model1)
oIndividual(ns1:file1)
oIndividual(ns1:file-path1)
typeOf(ns1:system-model1, ns:Model)
typeOf(ns1:file1, ns:File)
typeOf(ns1:file-path1, ns:FilePath)
property(ns1:system-model1, iof:serializedIn, ns1:file1)
property(ns1:file-path1, iof:designates, ns1:file1, right)
data(ns1:file-path1, rdfs:label, "C:\user\folder\file1")
data(ns1:file1, rdfs:label, "file1")
data(ns1:system-model1, rdfs:label, "system-model1")
@enduml