@startuml
!include C:\Users\arkop\git\IOF-Visual\ontopuml\iof.iuml
oClass(iof:TemporalInstantValueExpression)
oClass(bfo:TemporalInstant)
xSome(iof:TemporalInstantValueExpression, iof:isValueExpressionOfAtAllTimes, bfo:TemporalInstant)
oClass(time:TemporalPosition)
subClass(iof:TemporalInstantValueExpression, time:TemporalPosition)
xSomeData(iof:TemporalInstantValueExpression, iof:hasDateTimeInstantValue, xsd:dateTime, "", down)
oClass(time:GeneralDateTimeDescription)
subClass(time:GeneralDateTimeDescription, time:TemporalPosition)
oClass(time:TemporalUnit)
xSome(time:GeneralDateTimeDescription, time:unitType, time:TemporalUnit, "", down)
oIndividual(time:unitDay)
typeOf(time:unitDay, time:TemporalUnit)
oIndividual(time:unitHour)
typeOf(time:unitHour, time:TemporalUnit)
oIndividual(time:unitMinute)
typeOf(time:unitMinute, time:TemporalUnit)
oIndividual(time:unitMonth)
typeOf(time:unitMonth, time:TemporalUnit)
oIndividual(time:unitSecond)
typeOf(time:unitSecond, time:TemporalUnit)
oIndividual(time:unitWeek)
typeOf(time:unitWeek, time:TemporalUnit)
oIndividual(time:unitYear)
typeOf(time:unitYear, time:TemporalUnit)
oClass(time:TRS)
xSome(time:GeneralDateTimeDescription, time:hasTRS, time:TRS, "", right)
oClass(time:TimeZone)
xSome(time:GeneralDateTimeDescription, time:timeZone, time:TimeZone, "", right)
@enduml