@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml

class(ms, iof:MaterialState)
class(p, bfo:process)
subClass(ms, p)
class(ls, iof:LocationState)
subClass(ls, ms)
class(o, bfo:object)
class(s, bfo:site)
xOnly(ls, iof:hasObject, o)
xOnly(ls, iof:hasLocaton, s, "", right)
individual(t, ns:train1)
typeOf(t, o)
individual(st, ns:station1)
typeOf(st, s)
individual(ls1, ns:location-state-of-train1)
typeOf(ls1, ls)
property(ls1, iof:hasObject, t)
property(ls1, iof:hasLocation, st, right)
data(ls1, iof:hasTime, 10:00PM)
@enduml