@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, iof:MeasurementInformationContentEntity)
class(c2, iof:InformationContentEntity)
class(c3, iof:MeasuredValueExpression)
xSome(c1, bfo:hasContinuantPartAtAllTimes, c3, "",down)
class(c5, bfo:temporalRegion)
class(c6, bfo:specificallyDependentContinuant)
class(c7, iof:ProcessCharacteristic)
union(ce8, '["c5", "c6", "c7"]')
xSome(c1, iof:describes, ce8, "", down)
class(c9, bfo:process)
class(c10, bfo:processBoundary)
class(c11, bfo:independentContinuant)
class(c12, bfo:spatialRegion)
complement(ce13, "c12")
intersection(ce14, '["c11", "ce13"]')
union(ce15, '["c9", "c10", "ce14"]')
xSome(c1, iof:isAbout, ce15, "", down)
class(c16, iof:MeasurementProcess)
xSome(c1, iof:isOutputOf, c16,"",down)
subClass(c1, c2)
@enduml