@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml

' class(c1, iof:DesignSpecification)
' class(c2, iof:ComponentSlot)
individual(i1, ns1:tire-bead-spec)
individual(i2, ns1:tire-spec-1)
individual(i3, ns1:tire-bead-slot-1)
individual(i4, ns1:tire-bead-slot-2)
individual(i5, ns1:wheel-spec-1)
individual(i6, ns1:tire-mounting-rim-1)
individual(i7, ns1:tire-mounting-hole-1)
individual(i8, ns1:tire-mounting-rim-slot-1)
individual(i9, ns1:tire-mounting-rim-slot-2)
individual(i10, ns1:mounting-hole-slot-1)
individual(i11, ns1:mounting-hole-slot-2)
individual(i12, ns1:mounting-hole-slot-3)
individual(i13, ns1:mounting-hole-slot-4)
individual(i14, ns1:mounting-hole-slot-5)
individual(i15, ns1:wheel-assembly-spec-1)
individual(i16, ns1:wheel-slot-1)
individual(i17, ns1:tire-slot-1)
individual(i18, ns1:hub-spec-1)
individual(i19, ns1:bolt-hole-1)
individual(i20, ns1:bolt-hole-slot-1)
individual(i21, ns1:bolt-hole-slot-2)
individual(i22, ns1:bolt-hole-slot-3)
individual(i23, ns1:bolt-hole-slot-4)
individual(i24, ns1:bolt-hole-slot-5)
individual(i25, ns1:lug-bolt-spec-1)
individual(i26, ns1:wheel-hub-assembly-spec-1)
individual(i27, ns1:wheel-assembly-slot-1)
individual(i28, ns1:hub-slot-1)
individual(i29, ns1:lug-bolt-slot-1)
individual(i30, ns1:lug-bolt-slot-2)
individual(i31, ns1:lug-bolt-slot-3)
individual(i32, ns1:lug-bolt-slot-4)
individual(i33, ns1:lug-bolt-slot-5)
individual(i34, ns1:connection-slot-1)
individual(i35, ns1:fastener-slot-1)
individual(i36, ns1:connected-part-slot-1)
individual(i37, ns1:connected-part-slot-2)
individual(i38, ns1:tire_hub_joint_spec)
individual(i39, ns1:joint-slot)
' typeOf(i1, c1)
' typeOf(i5, c1)
' typeOf(i6, c1)
' typeOf(i7, c1)
' typeOf(i19, c1)
' typeOf(i27, c2)
' typeOf(i28, c2)
' typeOf(i29, c2)
' typeOf(i30, c2)
' typeOf(i31, c2)
' typeOf(i32, c2)
' typeOf(i33, c2)
property(i1, hasSlot, i34, down)
property(i1, fills, i3, up)
property(i1, fills, i4, up)
property(i2, hasSlot, i3, down)
property(i2, hasSlot, i4, down)
property(i2, fills, i17, up)
property(i5, hasSlot, i8, down)
property(i5, hasSlot, i9, down)
property(i5, hasSlot, i10, down)
property(i5, hasSlot, i11, down)
property(i5, hasSlot, i12, down)
property(i5, hasSlot, i13, down)
property(i5, hasSlot, i14, down)
property(i5, fills, i16, up)
property(i6, fills, i8, up)
property(i6, fills, i9, up)
property(i6, fills, i34, up)
property(i7, fills, i10, up)
property(i7, fills, i11, up)
property(i7, fills, i12, up)
property(i7, fills, i13, up)
property(i7, fills, i14, up)
property(i7, fills, i37, up)
property(i15, hasSlot, i16, down)
property(i15, hasSlot, i17, down)
property(i15, fills, i27, up)
property(i18, hasSlot, i20, down)
property(i18, hasSlot, i21, down)
property(i18, hasSlot, i22, down)
property(i18, hasSlot, i23, down)
property(i18, hasSlot, i24, down)
property(i18, fills, i28, up)
property(i19, fills, i20, up)
property(i19, fills, i21, up)
property(i19, fills, i22, up)
property(i19, fills, i23, up)
property(i19, fills, i24, up)
property(i19, fills, i36, up)
property(i25, fills, i29, up)
property(i25, fills, i30, up)
property(i25, fills, i31, up)
property(i25, fills, i32, up)
property(i25, fills, i33, up)
property(i25, fills, i35, up)
property(i26, hasSlot, i27, down)
property(i26, hasSlot, i28, down)
property(i26, hasSlot, i29, down)
property(i26, hasSlot, i30, down)
property(i26, hasSlot, i31, down)
property(i26, hasSlot, i32, down)
property(i26, hasSlot, i33, down)
property(i38, hasSlot, i35, down)
property(i38, hasSlot, i36, down)
property(i38, hasSlot, i37, down)
property(i26, hasSlot, i39, down)
property(i38, fills, i39, up)
@enduml