@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, iof:MaterialArtifact)
class(c2, bfo:Process)
class(c3, bfo:Function)
individual(i1, ns1:artifact1)
individual(i2, ns1:process1)
individual(i3, ns1:function1)
typeOf(i1, c1)
typeOf(i2, c2)
typeOf(i3, c3)
property(i1, participatesIn, i2)
property(i1, bearerOf, i3)
property(i2, realizes, i3)
property(i2, hasParticipant, i1)
property(i3, inheresIn, i1)
property(i3, hasRealization, i2)
@enduml
